# Generated by Django 4.1.3 on 2023-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user_id',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
